modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="Biome mod by MikeTheShadow and Eelt. Powered by Forge (credits to forge team for forge)." #optional
[[mods]] #mandatory
modId="expansivebiomes" #mandatory
version="0.0.0.3" #mandatory
displayName="Expansive Biomes" #mandatory
description='''Expansive Biomes adds more biomes to Minecraft 1.14.4. By: MikeTheShadow, and Eelt.'''